import boto3
import json

def analisar_cv_com_bedrock(texto_cv, texto_vaga):
    """
    Analyzes a resume against a job description using Amazon Bedrock.

    :param texto_cv: The text of the resume.
    :param texto_vaga: The text of the job description.
    :return: The analysis generated by the AI, or an error message.
    """
    try:
        # Create a Bedrock client
        # Substitua 'us-east-1' pela região da AWS que você configurou
        bedrock_client = boto3.client(service_name='bedrock-runtime', region_name='us-east-1')
        # Model ID
        model_id = "anthropic.claude-3-sonnet-20240229-v1:0"

        # Prompt engineering
        prompt = f"""
        Você é um recrutador "Bar Raiser" da Amazon. Sua tarefa é analisar o seguinte currículo em relação à vaga de emprego fornecida,
        com foco especial nos Princípios de Liderança da Amazon.

        Currículo:
        {texto_cv}

        Vaga de Emprego:
        {texto_vaga}

        Sua análise deve:
        1.  Avaliar a aderência do currículo à vaga, destacando pontos fortes e fracos.
        2.  Analisar o currículo sob a ótica dos Princípios de Liderança da Amazon, como "Customer Obsession", "Ownership", e "Invent and Simplify". Forneça exemplos do currículo que demonstrem (ou não) esses princípios.
        3.  Sugerir melhorias concretas no currículo. Para cada sugestão, mostre como reescrever trechos usando o método STAR (Situação, Tarefa, Ação, Resultado) para evidenciar o impacto das realizações do candidato.
        4.  Formate sua resposta final usando Markdown para garantir a legibilidade.
        """

        # Create the request body
        body = json.dumps({
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 4096,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ]
        })

        # Invoke the model
        response = bedrock_client.invoke_model(
            body=body,
            modelId=model_id,
            accept='application/json',
            contentType='application/json'
        )

        # Parse the response
        response_body = json.loads(response.get('body').read())
        analysis = response_body['content'][0]['text']

        return analysis

    except Exception as e:
        print(f"Erro ao analisar com o Bedrock: {e}")
        return f"Ocorreu um erro ao processar a sua solicitação. Verifique as configurações e credenciais da AWS. Erro: {e}"
